import type { Listing } from "./types";
import apt1 from "@/assets/listing-apartment-1.jpg";
import apt2 from "@/assets/listing-apartment-2.jpg";
import house1 from "@/assets/listing-house-1.jpg";
import land1 from "@/assets/listing-land-1.jpg";
import land2 from "@/assets/listing-land-2.jpg";
import shop1 from "@/assets/listing-shop-1.jpg";

const days = (n: number) => new Date(Date.now() + n * 86400000).toISOString();
const ago = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

export const SEED_LISTINGS: Listing[] = [
  {
    id: "seed-1",
    createdAt: ago(2),
    titleAr: "شقة 120م في وسط البلد — تشطيب سوبر لوكس",
    descriptionAr:
      "شقة مميزة في قلب سمالوط، الدور الثالث، ٣ غرف ومطبخ وحمامين. تشطيب حديث، عدادات مستقلة، قريبة من المدارس والأسواق. مناسبة للسكن العائلي مباشرة.",
    price: 650000,
    priceType: "sale",
    propertyType: "apartment",
    areaSqm: 120,
    rooms: 3,
    floor: 3,
    locationName: "سمالوط — وسط البلد",
    locationArea: "samalot",
    phone: "+201001234567",
    whatsapp: "+201001234567",
    images: [apt1, apt2],
    isFeatured: true,
    isApproved: true,
    packageType: "featured",
    listerType: "office",
    listerName: "مكتب النيل العقاري",
    expiresAt: days(58),
  },
  {
    id: "seed-2",
    createdAt: ago(5),
    titleAr: "منزل دورين بحوش في عزبة سلمان",
    descriptionAr:
      "منزل ريفي ٢٠٠م مبني، أرض ٣٠٠م، حوش خاص، بئر مياه، مدخل مستقل. مناسب لعائلة كبيرة أو للاستثمار الزراعي.",
    price: 480000,
    priceType: "sale",
    propertyType: "house",
    areaSqm: 200,
    rooms: 4,
    floor: 0,
    locationName: "عزبة سلمان",
    locationArea: "village",
    villageName: "عزبة سلمان",
    phone: "+201112223344",
    whatsapp: "+201112223344",
    images: [house1],
    isFeatured: false,
    isApproved: true,
    packageType: "basic",
    listerType: "individual",
    listerName: "أم أحمد",
    expiresAt: days(28),
  },
  {
    id: "seed-3",
    createdAt: ago(1),
    titleAr: "أرض زراعية ٣ قراريط — الشيخ فضل",
    descriptionAr:
      "أرض زراعية مميزة بجوار المصرف الرئيسي، رية مستمرة، مناسبة لزراعة الخضروات والفاكهة. تصلح للاستثمار طويل الأمد.",
    price: 220000,
    priceType: "sale",
    propertyType: "land_agri",
    areaSqm: 630,
    rooms: 0,
    floor: 0,
    locationName: "الشيخ فضل",
    locationArea: "village",
    villageName: "الشيخ فضل",
    phone: "+201234567890",
    whatsapp: "+201234567890",
    images: [land1],
    isFeatured: false,
    isApproved: true,
    packageType: "basic",
    listerType: "broker",
    listerName: "السمسار محمد",
    expiresAt: days(20),
  },
  {
    id: "seed-4",
    createdAt: ago(3),
    titleAr: "شقة للإيجار ٩٠م مفروشة بالكامل",
    descriptionAr:
      "شقة مفروشة بالكامل في شارع الجمهورية، مكيفة، إنترنت، مناسبة للسكن الفوري. الإيجار شامل المرافق.",
    price: 4500,
    priceType: "rent",
    propertyType: "apartment",
    areaSqm: 90,
    rooms: 2,
    floor: 2,
    locationName: "سمالوط — وسط البلد",
    locationArea: "samalot",
    phone: "+201556677889",
    whatsapp: "+201556677889",
    images: [apt2, apt1],
    isFeatured: false,
    isApproved: true,
    packageType: "basic",
    listerType: "individual",
    listerName: "أحمد محمود",
    expiresAt: days(25),
  },
  {
    id: "seed-5",
    createdAt: ago(6),
    titleAr: "محل تجاري ٤٠م على شارع رئيسي",
    descriptionAr:
      "محل بمدخلين على شارع رئيسي مزدحم، مناسب لأي نشاط تجاري. واجهة كبيرة، حمام داخلي، عداد مستقل.",
    price: 350000,
    priceType: "sale",
    propertyType: "commercial",
    areaSqm: 40,
    rooms: 0,
    floor: 0,
    locationName: "سمالوط — وسط البلد",
    locationArea: "samalot",
    phone: "+201009998877",
    whatsapp: "+201009998877",
    images: [shop1],
    isFeatured: false,
    isApproved: true,
    packageType: "basic",
    listerType: "broker",
    listerName: "مكتب الأمانة",
    expiresAt: days(22),
  },
  {
    id: "seed-6",
    createdAt: ago(7),
    titleAr: "أرض بناء ٢٠٠م — موقع متميز",
    descriptionAr:
      "قطعة أرض جاهزة للبناء، التراخيص متوفرة، شوارع مرصوفة من جهتين. مناسبة لبناء عمارة سكنية أو فيلا.",
    price: 380000,
    priceType: "sale",
    propertyType: "land_build",
    areaSqm: 200,
    rooms: 0,
    floor: 0,
    locationName: "بني أحمد",
    locationArea: "village",
    villageName: "بني أحمد",
    phone: "+201223344556",
    whatsapp: "+201223344556",
    images: [land2],
    isFeatured: true,
    isApproved: true,
    packageType: "featured",
    listerType: "office",
    listerName: "مكتب النيل العقاري",
    expiresAt: days(55),
  },
  {
    id: "seed-7",
    createdAt: ago(0),
    titleAr: "شقة ٨٥م للإيجار — قريبة من المدرسة",
    descriptionAr:
      "شقة فاضية بدون فرش، الدور الأول، ٢ غرفة ومطبخ وحمام. قريبة جداً من مدرسة سمالوط الثانوية.",
    price: 2500,
    priceType: "rent",
    propertyType: "apartment",
    areaSqm: 85,
    rooms: 2,
    floor: 1,
    locationName: "سمالوط — وسط البلد",
    locationArea: "samalot",
    phone: "+201112345678",
    whatsapp: "+201112345678",
    images: [apt1],
    isFeatured: false,
    isApproved: true,
    packageType: "basic",
    listerType: "individual",
    listerName: "ست هدى",
    expiresAt: days(29),
  },
  {
    id: "seed-pending",
    createdAt: ago(0),
    titleAr: "[في انتظار الموافقة] منزل في دير البرشا",
    descriptionAr:
      "منزل ريفي ١٥٠م، طابقين، حديقة صغيرة. مرفق صور وكامل التفاصيل عند التواصل.",
    price: 320000,
    priceType: "sale",
    propertyType: "house",
    areaSqm: 150,
    rooms: 3,
    floor: 0,
    locationName: "دير البرشا",
    locationArea: "village",
    villageName: "دير البرشا",
    phone: "+201998877665",
    whatsapp: "+201998877665",
    images: [house1],
    isFeatured: false,
    isApproved: false,
    packageType: "basic",
    listerType: "individual",
    listerName: "محمد علي",
    expiresAt: days(30),
  },
];
